### ISSUE TITLE
Newbie to Github - How do I install this MP?

### ISSUE THREAD

**Issue by sbanyas** [rafabu/SCOM-PKICertificateMP#5]
I'm a newbie to Gethub.  How do I get the MP files to install?

**Comment by sepeck** [comment]
Click on the Clone or Download button. Then choose Download ZIP. Unzip once downloaded.

**Comment by durgadevisandy** [comment]
I do have same question. did anyone install this pack?

**Comment by shawnzzzy** [comment]
Here is the process that i had to use to successfully build the MP:

1.	Install Visual Studio 2017.
2.	Install Visual Studio Authoring Extensions
https://www.microsoft.com/en-us/download/details.aspx?id=30169
3.	Download the newest version from here:
https://github.com/rafabu/SCOM-PKICertificateMP
4.	Download as Zip and extract files to C:\VisualStudioProjects\PKI-MP
5.	Go to C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools  
6.	Right Click Developer Command Prompt for VS2017 and select Run as Administrator
7.	Type the following to create a Key File (This is required to seal the management pack) :
sn.exe -k c:\temp\SCOMKey.snk
8.	Open Windows Explorer and paste this path into the location bar 
C:\Documents and Settings\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys
9.	Give your user full control to this path. (Must be your user account not just the administrators group.)
10.	Run Visual Studio 2017
11.	File -> Open Project and then browse to C:\VisualStudioProjects\PKI-MP.
12.	Select the Cert_V3.sln file.
13.	Navigate to Project -> Vert_V3 properties.
14.	Choose the Built tab on the left and click the box Generate sealed and signed management pack.
15.	Click the Browse button by the Key File and choose the key file you created in step 6.
16.	Delete the Microsoft.Windows.Server.Library reference file from the Cert_V3_QuickStart_OR project because the file reference in missing.
17.	Right click on the References folder under Cert_V3_QuickStart_OR and choose Add Reference.
18.	On the Browse tab paste C:\Program Files (x86)\System Center Visual Studio Authoring Extensions\References\OM2016 into the file name field and then choose Microsoft.Windows.Server.Library.mp file.
19.	In the properties box for the reference, make sure that the Alias is set to WindowsServer.
20.	Initiate a build on the solution making sure that it’s in Release mode.
21.	If it successfully builds with no errors or warnings you can open operations manager.
22.	Go to the Administration tab -> Installed Management packs and import all the management packs, (mpb files), from the release folders for each project in the solution.

**Comment by randomnote1** [comment]
> Click on the Clone or Download button. Then choose Download ZIP. Unzip once downloaded.

This is the correct answer. Thanks!

**Comment by rafabu** [comment]
> Here is the process that i had to use to successfully build the MP:
> 
> 1. Install Visual Studio 2017.
> 2. Install Visual Studio Authoring Extensions
>    https://www.microsoft.com/en-us/download/details.aspx?id=30169
> 3. Download the newest version from here:
>    https://github.com/rafabu/SCOM-PKICertificateMP
> 4. Download as Zip and extract files to C:\VisualStudioProjects\PKI-MP
> 5. Go to C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools
> 6. Right Click Developer Command Prompt for VS2017 and select Run as Administrator
> 7. Type the following to create a Key File (This is required to seal the management pack) :
>    sn.exe -k c:\temp\SCOMKey.snk
> 8. Open Windows Explorer and paste this path into the location bar
>    C:\Documents and Settings\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys
> 9. Give your user full control to this path. (Must be your user account not just the administrators group.)
> 10. Run Visual Studio 2017
> 11. File -> Open Project and then browse to C:\VisualStudioProjects\PKI-MP.
> 12. Select the Cert_V3.sln file.
> 13. Navigate to Project -> Vert_V3 properties.
> 14. Choose the Built tab on the left and click the box Generate sealed and signed management pack.
> 15. Click the Browse button by the Key File and choose the key file you created in step 6.
> 16. Delete the Microsoft.Windows.Server.Library reference file from the Cert_V3_QuickStart_OR project because the file reference in missing.
> 17. Right click on the References folder under Cert_V3_QuickStart_OR and choose Add Reference.
> 18. On the Browse tab paste C:\Program Files (x86)\System Center Visual Studio Authoring Extensions\References\OM2016 into the file name field and then choose Microsoft.Windows.Server.Library.mp file.
> 19. In the properties box for the reference, make sure that the Alias is set to WindowsServer.
> 20. Initiate a build on the solution making sure that it’s in Release mode.
> 21. If it successfully builds with no errors or warnings you can open operations manager.
> 22. Go to the Administration tab -> Installed Management packs and import all the management packs, (mpb files), from the release folders for each project in the solution.

This is an amazingly well layed out description of how to build your own version of the MP! However; if a binary (the actual sealed mpb files) is required, you could also download it from the release page: [https://github.com/rafabu/SCOM-PKICertificateMP/releases](https://github.com/rafabu/SCOM-PKICertificateMP/releases) (make sure you get the zip file).

**Comment by durgadevisandy** [comment]
Thanks Very much for you response! I will try this.

**Comment by shawnzzzy** [comment]
> > Here is the process that i had to use to successfully build the MP:
> > 
.......
> This is an amazingly well layed out description of how to build your own version of the MP! However; if a binary (the actual sealed mpb files) is required, you could also download it from the release page: https://github.com/rafabu/SCOM-PKICertificateMP/releases (make sure you get the zip file).

Sorry, i'm new to GitHub, didn't know that the release tab provided the binary. I've always been interested in building my own management packs anyway. :)
